import { writeFile } from 'fs/promises';
import { AnalysisResult } from '../agent/analyzer.js';

export class GitHubReporter {
  /**
   * Generates a comprehensive GitHub Job Summary report
   */
  static generateJobSummary(
    results: Map<string, AnalysisResult>,
    prNumber: number,
    repository: string
  ): string {
    const totalFiles = results.size;
    const avgScore = Array.from(results.values()).reduce((sum, r) => sum + r.score, 0) / totalFiles;
    const totalCritical = Array.from(results.values()).reduce((sum, r) => sum + r.critical.length, 0);
    const totalWarnings = Array.from(results.values()).reduce((sum, r) => sum + r.warnings.length, 0);
    const totalSuggestions = Array.from(results.values()).reduce((sum, r) => sum + r.suggestions.length, 0);
    const totalGoodPractices = Array.from(results.values()).reduce((sum, r) => sum + r.goodPractices.length, 0);

    let report = `# 📊 SQL Schema Analysis - Detailed Report\n\n`;
    report += `**Repository:** ${repository} | **PR:** #${prNumber}\n\n`;
    report += `---\n\n`;

    // Executive Dashboard
    report += `## 📈 Executive Dashboard\n\n`;
    report += `### Overall Metrics\n\n`;
    report += `| Metric | Value | Status |\n`;
    report += `|--------|-------|--------|\n`;
    report += `| Files Analyzed | ${totalFiles} | ℹ️ |\n`;
    report += `| Average Score | **${avgScore.toFixed(1)}/10** | ${this.getScoreBadge(avgScore)} |\n`;
    report += `| Critical Issues | ${totalCritical} | ${totalCritical > 0 ? '🚨' : '✅'} |\n`;
    report += `| Warnings | ${totalWarnings} | ${totalWarnings > 0 ? '⚠️' : '✅'} |\n`;
    report += `| Suggestions | ${totalSuggestions} | ${totalSuggestions > 0 ? 'ℹ️' : '✅'} |\n`;
    report += `| Good Practices | ${totalGoodPractices} | ✅ |\n\n`;

    // Score Distribution
    report += `### 📊 Score Distribution\n\n`;
    report += this.generateScoreDistribution(results);
    report += `\n\n`;

    // Issue Breakdown
    report += `### 🔍 Issue Breakdown by Category\n\n`;
    report += this.generateIssueBreakdown(results);
    report += `\n\n`;

    // File-by-File Analysis
    report += `## 📁 Detailed File Analysis\n\n`;
    for (const [filename, result] of results) {
      report += this.generateDetailedFileReport(filename, result);
      report += `\n---\n\n`;
    }

    // Recommendations
    report += `## 🎯 Consolidated Recommendations\n\n`;
    report += this.generateConsolidatedRecommendations(results);
    report += `\n\n`;

    // Security Checklist
    report += `## 🔒 Security Checklist\n\n`;
    report += this.generateSecurityChecklist(results);
    report += `\n\n`;

    // Next Steps
    report += `## 📋 Next Steps\n\n`;
    if (totalCritical > 0) {
      report += `1. ❗ **CRITICAL**: Address all ${totalCritical} critical issue(s) immediately\n`;
      report += `2. Review ${totalWarnings} warning(s) and implement high-priority fixes\n`;
      report += `3. Consider ${totalSuggestions} suggestion(s) for optimization\n`;
      report += `4. Re-run analysis after fixes to verify improvements\n\n`;
    } else if (totalWarnings > 0) {
      report += `1. ✅ No critical issues - good job!\n`;
      report += `2. Review ${totalWarnings} warning(s) and prioritize fixes\n`;
      report += `3. Consider ${totalSuggestions} suggestion(s) for optimization\n`;
      report += `4. Optional: Re-run analysis after improvements\n\n`;
    } else {
      report += `1. 🎉 Excellent work! All files follow best practices\n`;
      report += `2. ${totalSuggestions > 0 ? `Consider ${totalSuggestions} suggestion(s) for further optimization` : 'No improvements needed'}\n`;
      report += `3. Ready to merge!\n\n`;
    }

    report += `---\n\n`;
    report += `*Report generated by Supabase SQL Agent powered by Claude AI*\n`;

    return report;
  }

  /**
   * Writes the job summary to GitHub's special file
   */
  static async writeJobSummary(content: string): Promise<void> {
    const summaryFile = process.env.GITHUB_STEP_SUMMARY;

    if (!summaryFile) {
      console.warn('⚠️  GITHUB_STEP_SUMMARY not set. Running outside GitHub Actions?');
      console.log('📋 Job Summary (would be written to GitHub):\n');
      console.log(content);
      return;
    }

    try {
      await writeFile(summaryFile, content, { flag: 'a' }); // Append mode
      console.log('✅ Job summary written to GitHub Actions');
    } catch (error) {
      console.error('❌ Failed to write job summary:', error);
    }
  }

  private static getScoreBadge(score: number): string {
    if (score >= 9) return '🟢';
    if (score >= 7) return '🟡';
    if (score >= 5) return '🟠';
    return '🔴';
  }

  private static generateScoreDistribution(results: Map<string, AnalysisResult>): string {
    const scores = Array.from(results.values()).map((r) => r.score);
    const excellent = scores.filter((s) => s >= 9).length;
    const good = scores.filter((s) => s >= 7 && s < 9).length;
    const needsWork = scores.filter((s) => s >= 5 && s < 7).length;
    const critical = scores.filter((s) => s < 5).length;

    let dist = `\`\`\`\n`;
    dist += `🟢 Excellent (9-10):  ${excellent} file(s) ${'█'.repeat(excellent * 3)}\n`;
    dist += `🟡 Good (7-8):        ${good} file(s) ${'█'.repeat(good * 3)}\n`;
    dist += `🟠 Needs Work (5-6):  ${needsWork} file(s) ${'█'.repeat(needsWork * 3)}\n`;
    dist += `🔴 Critical (<5):     ${critical} file(s) ${'█'.repeat(critical * 3)}\n`;
    dist += `\`\`\``;

    return dist;
  }

  private static generateIssueBreakdown(results: Map<string, AnalysisResult>): string {
    const allCritical = Array.from(results.values()).flatMap((r) => r.critical);
    const allWarnings = Array.from(results.values()).flatMap((r) => r.warnings);

    // Categorize issues by type
    const categories: Record<string, number> = {
      'Row Level Security': 0,
      'Foreign Keys': 0,
      'Indexes': 0,
      'Credentials/Secrets': 0,
      'Constraints': 0,
      'Other': 0,
    };

    [...allCritical, ...allWarnings].forEach((issue) => {
      const text = 'issue' in issue ? issue.issue : '';
      if (text.toLowerCase().includes('rls') || text.toLowerCase().includes('row level')) {
        categories['Row Level Security']++;
      } else if (text.toLowerCase().includes('foreign key')) {
        categories['Foreign Keys']++;
      } else if (text.toLowerCase().includes('index')) {
        categories['Indexes']++;
      } else if (text.toLowerCase().includes('secret') || text.toLowerCase().includes('credential')) {
        categories['Credentials/Secrets']++;
      } else if (text.toLowerCase().includes('constraint')) {
        categories['Constraints']++;
      } else {
        categories['Other']++;
      }
    });

    let breakdown = `| Category | Count |\n|----------|-------|\n`;
    for (const [category, count] of Object.entries(categories)) {
      if (count > 0) {
        breakdown += `| ${category} | ${count} |\n`;
      }
    }

    return breakdown;
  }

  private static generateDetailedFileReport(filename: string, result: AnalysisResult): string {
    let report = `### 📄 \`${filename}\`\n\n`;
    report += `**Score:** ${result.score}/10 ${this.getScoreBadge(result.score)}\n\n`;
    report += `**Summary:** ${result.summary}\n\n`;

    if (result.critical.length > 0) {
      report += `#### 🚨 Critical Issues (${result.critical.length})\n\n`;
      result.critical.forEach((issue, idx) => {
        report += `${idx + 1}. ${issue.issue}\n`;
        report += `   - **Risk:** ${issue.risk}\n`;
      });
      report += `\n`;
    }

    if (result.warnings.length > 0) {
      report += `#### ⚠️ Warnings (${result.warnings.length})\n\n`;
      result.warnings.forEach((warning, idx) => {
        report += `${idx + 1}. ${warning.issue}\n`;
      });
      report += `\n`;
    }

    if (result.suggestions.length > 0) {
      report += `#### ℹ️ Suggestions (${result.suggestions.length})\n\n`;
      result.suggestions.forEach((suggestion, idx) => {
        report += `${idx + 1}. ${suggestion.suggestion}\n`;
      });
      report += `\n`;
    }

    if (result.goodPractices.length > 0) {
      report += `#### ✅ Good Practices (${result.goodPractices.length})\n\n`;
      result.goodPractices.forEach((practice) => {
        report += `- ${practice}\n`;
      });
      report += `\n`;
    }

    return report;
  }

  private static generateConsolidatedRecommendations(results: Map<string, AnalysisResult>): string {
    const allPlans = Array.from(results.values()).flatMap((r) => r.actionPlan);

    if (allPlans.length === 0) {
      return `No specific action items - all files are in excellent shape! 🎉\n`;
    }

    let recs = `### Priority Action Items\n\n`;
    allPlans.forEach((plan, idx) => {
      recs += `${idx + 1}. ${plan}\n`;
    });

    return recs;
  }

  private static generateSecurityChecklist(results: Map<string, AnalysisResult>): string {
    const allCritical = Array.from(results.values()).flatMap((r) => r.critical);
    const allWarnings = Array.from(results.values()).flatMap((r) => r.warnings);

    const hasRlsIssues = [...allCritical, ...allWarnings].some((i) =>
      ('issue' in i ? i.issue : '').toLowerCase().includes('rls')
    );
    const hasFkIssues = [...allCritical, ...allWarnings].some((i) =>
      ('issue' in i ? i.issue : '').toLowerCase().includes('foreign key')
    );
    const hasIndexIssues = [...allCritical, ...allWarnings].some((i) =>
      ('issue' in i ? i.issue : '').toLowerCase().includes('index')
    );
    const hasSecretIssues = [...allCritical, ...allWarnings].some((i) =>
      ('issue' in i ? i.issue : '').toLowerCase().includes('secret')
    );

    let checklist = `| Security Item | Status |\n|---------------|--------|\n`;
    checklist += `| Row Level Security (RLS) Enabled | ${hasRlsIssues ? '❌ Issues Found' : '✅ Pass'} |\n`;
    checklist += `| Foreign Key Constraints | ${hasFkIssues ? '⚠️ Issues Found' : '✅ Pass'} |\n`;
    checklist += `| Performance Indexes | ${hasIndexIssues ? '⚠️ Issues Found' : '✅ Pass'} |\n`;
    checklist += `| No Exposed Secrets | ${hasSecretIssues ? '🚨 CRITICAL' : '✅ Pass'} |\n`;

    return checklist;
  }
}
