-- WARNING: This schema is for context only and is not meant to be run.
-- Table order and constraints may not be valid for execution.

CREATE TABLE public.admin_disbursements (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  tenant_id uuid NOT NULL,
  admin_user_id uuid NOT NULL,
  amount_points numeric NOT NULL CHECK (amount_points > 0::numeric),
  reason text,
  reference_user_id uuid,
  cost_center_id uuid,
  idempotency_key text,
  created_at timestamp with time zone DEFAULT now(),
  CONSTRAINT admin_disbursements_pkey PRIMARY KEY (id),
  CONSTRAINT admin_disbursements_tenant_id_fkey FOREIGN KEY (tenant_id) REFERENCES public.tenants(id)
);
CREATE TABLE public.ai_categorization_log (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  tenant_id uuid NOT NULL,
  reward_item_id uuid NOT NULL,
  suggested_categories jsonb NOT NULL,
  action_taken text NOT NULL CHECK (action_taken = ANY (ARRAY['auto_assigned'::text, 'needs_review'::text, 'rejected'::text])),
  assigned_by text,
  created_at timestamp with time zone DEFAULT now(),
  CONSTRAINT ai_categorization_log_pkey PRIMARY KEY (id),
  CONSTRAINT fk_tenant FOREIGN KEY (tenant_id) REFERENCES public.tenants(id)
);
CREATE TABLE public.ai_suggestions (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  user_id uuid NOT NULL,
  tenant_id uuid NOT NULL,
  category text NOT NULL CHECK (category = ANY (ARRAY['growth'::text, 'recognition'::text])),
  type text NOT NULL,
  title text NOT NULL,
  description text NOT NULL,
  objective text NOT NULL,
  scope text NOT NULL,
  audience text NOT NULL,
  estimated_participants integer,
  suggested_date text,
  points integer,
  duration text,
  suggestion_data jsonb NOT NULL,
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  CONSTRAINT ai_suggestions_pkey PRIMARY KEY (id),
  CONSTRAINT ai_suggestions_user_id_fkey FOREIGN KEY (user_id) REFERENCES auth.users(id),
  CONSTRAINT ai_suggestions_tenant_id_fkey FOREIGN KEY (tenant_id) REFERENCES public.tenants(id)
);
CREATE TABLE public.api_keys (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  tenant_id uuid NOT NULL,
  user_id uuid NOT NULL,
  key text NOT NULL UNIQUE,
  name text NOT NULL,
  description text,
  is_active boolean DEFAULT true,
  last_used_at timestamp with time zone,
  created_at timestamp with time zone DEFAULT now(),
  created_by uuid,
  expires_at timestamp with time zone,
  metadata jsonb DEFAULT '{}'::jsonb,
  CONSTRAINT api_keys_pkey PRIMARY KEY (id),
  CONSTRAINT api_keys_tenant_id_fkey FOREIGN KEY (tenant_id) REFERENCES public.tenants(id),
  CONSTRAINT api_keys_user_id_fkey FOREIGN KEY (user_id) REFERENCES auth.users(id),
  CONSTRAINT api_keys_created_by_fkey FOREIGN KEY (created_by) REFERENCES auth.users(id)
);
CREATE TABLE public.api_rate_limits (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  tenant_id uuid NOT NULL,
  user_id uuid NOT NULL,
  endpoint text NOT NULL,
  request_count integer NOT NULL DEFAULT 0,
  window_start timestamp with time zone NOT NULL DEFAULT now(),
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  updated_at timestamp with time zone NOT NULL DEFAULT now(),
  CONSTRAINT api_rate_limits_pkey PRIMARY KEY (id)
);
CREATE TABLE public.audit_logs (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  tenant_id uuid NOT NULL,
  user_id uuid,
  action text NOT NULL,
  resource_type text NOT NULL,
  resource_id uuid NOT NULL,
  old_values jsonb,
  new_values jsonb,
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  CONSTRAINT audit_logs_pkey PRIMARY KEY (id),
  CONSTRAINT audit_logs_tenant_id_fkey FOREIGN KEY (tenant_id) REFERENCES public.tenants(id),
  CONSTRAINT audit_logs_user_id_fkey FOREIGN KEY (user_id) REFERENCES auth.users(id)
);
CREATE TABLE public.automatic_events (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  tenant_id uuid NOT NULL,
  name text NOT NULL,
  description text NOT NULL,
  icon text NOT NULL,
  color text NOT NULL,
  bg_color text NOT NULL,
  trigger_type text NOT NULL CHECK (trigger_type = ANY (ARRAY['fixed_date'::text, 'dynamic_variable'::text, 'dynamic_with_offset'::text, 'calendar_variable'::text, 'integration'::text])),
  trigger_source text,
  default_points integer,
  ecard_template text,
  associated_badges ARRAY DEFAULT ARRAY[]::text[],
  associated_values ARRAY DEFAULT ARRAY[]::text[],
  category text NOT NULL,
  monthly_triggers integer DEFAULT 0,
  status text NOT NULL DEFAULT 'draft'::text,
  active boolean NOT NULL DEFAULT false,
  archived_at timestamp with time zone,
  version integer NOT NULL DEFAULT 1,
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  created_by uuid,
  updated_at timestamp with time zone NOT NULL DEFAULT now(),
  fixed_points integer NOT NULL DEFAULT 50,
  frequency_type text NOT NULL DEFAULT 'once_per_user_per_year'::text CHECK (frequency_type = ANY (ARRAY['once_per_user'::text, 'once_per_user_per_year'::text])),
  dynamic_variable text,
  fixed_date date,
  offset_value integer,
  offset_unit text CHECK (offset_unit IS NULL OR (offset_unit = ANY (ARRAY['days'::text, 'months'::text, 'years'::text]))),
  calendar_event_type text,
  next_occurrence_date date,
  next_occurrence_description text,
  filters jsonb DEFAULT '[]'::jsonb,
  CONSTRAINT automatic_events_pkey PRIMARY KEY (id)
);
CREATE TABLE public.awards (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  tenant_id uuid NOT NULL,
  name text NOT NULL,
  description text NOT NULL,
  icon text NOT NULL,
  color text NOT NULL,
  bg_color text NOT NULL,
  scope USER-DEFINED NOT NULL DEFAULT 'individual'::award_scope,
  periodicity USER-DEFINED NOT NULL DEFAULT 'monthly'::award_periodicity,
  winners_count integer NOT NULL DEFAULT 1 CHECK (winners_count > 0 AND winners_count <= 100),
  winners_by_segment boolean NOT NULL DEFAULT false,
  nomination_duration integer NOT NULL DEFAULT 7 CHECK (nomination_duration > 0 AND nomination_duration <= 90),
  voting_duration integer NOT NULL DEFAULT 5 CHECK (voting_duration > 0 AND voting_duration <= 30),
  announcement_date timestamp with time zone,
  who_can_nominate USER-DEFINED NOT NULL DEFAULT 'all'::award_eligibility,
  who_can_be_nominated USER-DEFINED NOT NULL DEFAULT 'all'::award_eligibility,
  custom_nominators ARRAY,
  custom_eligible ARRAY,
  voting_mode USER-DEFINED NOT NULL DEFAULT 'public'::award_voting_mode,
  jury_members ARRAY,
  public_vote_weight integer CHECK (public_vote_weight >= 0 AND public_vote_weight <= 100),
  jury_vote_weight integer CHECK (jury_vote_weight >= 0 AND jury_vote_weight <= 100),
  status USER-DEFINED NOT NULL DEFAULT 'draft'::award_status,
  current_phase USER-DEFINED NOT NULL DEFAULT 'setup'::award_phase,
  nominations_count integer NOT NULL DEFAULT 0,
  candidates_count integer NOT NULL DEFAULT 0,
  votes_count integer NOT NULL DEFAULT 0,
  winners ARRAY DEFAULT ARRAY[]::text[],
  notify_on_nomination boolean NOT NULL DEFAULT true,
  notify_on_voting boolean NOT NULL DEFAULT true,
  notify_winners boolean NOT NULL DEFAULT true,
  slack_integration boolean NOT NULL DEFAULT false,
  teams_integration boolean NOT NULL DEFAULT false,
  created_by uuid,
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  updated_at timestamp with time zone NOT NULL DEFAULT now(),
  archived_at timestamp with time zone,
  version integer NOT NULL DEFAULT 1,
  skip_nomination_phase boolean NOT NULL DEFAULT false,
  predefined_candidates ARRAY,
  points_distribution_mode text DEFAULT 'per_winner'::text CHECK (points_distribution_mode = ANY (ARRAY['per_winner'::text, 'total_pool'::text])),
  total_points integer,
  second_place_points integer,
  third_place_points integer,
  associated_values ARRAY DEFAULT ARRAY[]::text[],
  associated_badges ARRAY DEFAULT ARRAY[]::uuid[],
  CONSTRAINT awards_pkey PRIMARY KEY (id)
);
CREATE TABLE public.badges (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  tenant_id uuid NOT NULL,
  name text NOT NULL,
  description text NOT NULL,
  icon text NOT NULL,
  color text NOT NULL,
  bg_color text NOT NULL,
  associated_values ARRAY DEFAULT ARRAY[]::text[],
  category USER-DEFINED NOT NULL DEFAULT 'values'::badge_category,
  awarded_count integer NOT NULL DEFAULT 0,
  active boolean NOT NULL DEFAULT true,
  status USER-DEFINED NOT NULL DEFAULT 'draft'::badge_status,
  archived_at timestamp with time zone,
  version integer NOT NULL DEFAULT 1,
  visibility USER-DEFINED NOT NULL DEFAULT 'public'::visibility_type,
  requires_approval boolean NOT NULL DEFAULT false,
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  updated_at timestamp with time zone NOT NULL DEFAULT now(),
  department_ids ARRAY,
  CONSTRAINT badges_pkey PRIMARY KEY (id)
);
CREATE TABLE public.batch_processing_queue (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  tenant_id uuid NOT NULL,
  batch_id uuid NOT NULL,
  status USER-DEFINED NOT NULL DEFAULT 'queued'::batch_queue_status,
  started_at timestamp with time zone,
  completed_at timestamp with time zone,
  error_message text,
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  updated_at timestamp with time zone NOT NULL DEFAULT now(),
  CONSTRAINT batch_processing_queue_pkey PRIMARY KEY (id),
  CONSTRAINT batch_processing_queue_batch_id_fkey FOREIGN KEY (batch_id) REFERENCES public.gift_card_batches(id)
);
CREATE TABLE public.batch_recipients (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  batch_id uuid NOT NULL,
  recipient_type text NOT NULL CHECK (recipient_type = ANY (ARRAY['user'::text, 'team'::text, 'department'::text])),
  recipient_id uuid NOT NULL,
  recipient_name text NOT NULL,
  recipient_email text NOT NULL,
  created_at timestamp with time zone DEFAULT now(),
  CONSTRAINT batch_recipients_pkey PRIMARY KEY (id),
  CONSTRAINT batch_recipients_batch_id_fkey FOREIGN KEY (batch_id) REFERENCES public.gift_card_batches(id)
);
CREATE TABLE public.brands (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  domain text NOT NULL UNIQUE,
  name text NOT NULL,
  slug text NOT NULL UNIQUE,
  theme_config jsonb DEFAULT '{"logo": "/logos/brand-default.svg", "fonts": {"heading": "Inter, sans-serif", "primary": "Inter, sans-serif"}, "colors": {"accent": "350 85% 96%", "primary": "350 78% 58%", "secondary": "350 85% 96%", "background": "0 0% 99.5%", "foreground": "220 8% 18%", "primaryHover": "350 66% 52%"}}'::jsonb,
  features jsonb DEFAULT '{"awards": true, "challenges": true, "ai_suggestions": false, "rewards_catalog": true, "white_label_mode": false}'::jsonb,
  settings jsonb DEFAULT '{"default_locale": "es-ES", "allow_self_signup": false, "supported_currencies": ["USD", "EUR", "CLP"], "require_admin_approval": true}'::jsonb,
  is_active boolean DEFAULT true,
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  email_config jsonb DEFAULT '{"reply_to": null, "template": {"header_bg": null, "accent_color": null, "button_color": null}, "from_name": null}'::jsonb,
  CONSTRAINT brands_pkey PRIMARY KEY (id)
);
CREATE TABLE public.budget_overrides (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  tenant_id uuid NOT NULL,
  scope_id uuid NOT NULL,
  period_start date NOT NULL,
  period_end date NOT NULL,
  override_points integer,
  delta_percent numeric,
  note text NOT NULL,
  created_by uuid NOT NULL,
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  CONSTRAINT budget_overrides_pkey PRIMARY KEY (id),
  CONSTRAINT budget_overrides_scope_id_fkey FOREIGN KEY (scope_id) REFERENCES public.recognition_scopes(id)
);
CREATE TABLE public.budget_policies (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  tenant_id uuid NOT NULL,
  name text NOT NULL,
  formula_type text NOT NULL CHECK (formula_type = ANY (ARRAY['fixed'::text, 'tiered'::text, 'dynamic'::text, 'ml'::text])),
  weights jsonb,
  metadata jsonb,
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  CONSTRAINT budget_policies_pkey PRIMARY KEY (id)
);
CREATE TABLE public.budget_scope_limits (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  tenant_id uuid NOT NULL,
  parent_scope_id uuid NOT NULL,
  child_scope_type text NOT NULL CHECK (child_scope_type = ANY (ARRAY['department'::text, 'team'::text, 'manager'::text, 'user'::text])),
  max_hard_cap integer,
  max_soft_cap integer,
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  updated_at timestamp with time zone NOT NULL DEFAULT now(),
  CONSTRAINT budget_scope_limits_pkey PRIMARY KEY (id),
  CONSTRAINT budget_scope_limits_parent_scope_id_fkey FOREIGN KEY (parent_scope_id) REFERENCES public.recognition_scopes(id)
);
CREATE TABLE public.budget_templates (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  tenant_id uuid NOT NULL,
  scope_type text NOT NULL CHECK (scope_type = ANY (ARRAY['company'::text, 'department'::text, 'team'::text, 'manager'::text, 'user'::text])),
  default_hard_cap integer NOT NULL,
  default_soft_cap integer NOT NULL,
  is_active boolean NOT NULL DEFAULT true,
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  updated_at timestamp with time zone NOT NULL DEFAULT now(),
  period_start date,
  period_end date,
  CONSTRAINT budget_templates_pkey PRIMARY KEY (id)
);
CREATE TABLE public.catalog_sync_status (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  tenant_id uuid NOT NULL,
  provider_id text NOT NULL,
  status text NOT NULL CHECK (status = ANY (ARRAY['processing'::text, 'completed'::text, 'failed'::text])),
  progress jsonb DEFAULT '{"total": 0, "processed": 0, "current_product": "", "available_countries": [], "available_currencies": []}'::jsonb,
  started_at timestamp with time zone DEFAULT now(),
  completed_at timestamp with time zone,
  error_message text,
  created_at timestamp with time zone DEFAULT now(),
  metadata jsonb DEFAULT '{}'::jsonb,
  CONSTRAINT catalog_sync_status_pkey PRIMARY KEY (id)
);
CREATE TABLE public.challenge_actions (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  challenge_id uuid NOT NULL,
  user_id uuid NOT NULL,
  tenant_id uuid NOT NULL,
  action_type USER-DEFINED NOT NULL,
  description text,
  value integer NOT NULL DEFAULT 1,
  points_awarded integer NOT NULL DEFAULT 1,
  metadata jsonb DEFAULT '{}'::jsonb,
  evidence_url text,
  validated_by uuid,
  validated_at timestamp with time zone,
  validation_status USER-DEFINED DEFAULT 'pending'::challenge_validation_status,
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  updated_at timestamp with time zone NOT NULL DEFAULT now(),
  CONSTRAINT challenge_actions_pkey PRIMARY KEY (id),
  CONSTRAINT challenge_actions_challenge_id_fkey FOREIGN KEY (challenge_id) REFERENCES public.challenges(id),
  CONSTRAINT challenge_actions_tenant_id_fkey FOREIGN KEY (tenant_id) REFERENCES public.tenants(id)
);
CREATE TABLE public.challenge_nudge_logs (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  nudge_id uuid NOT NULL,
  user_id uuid NOT NULL,
  sent_at timestamp with time zone NOT NULL DEFAULT now(),
  delivery_status text DEFAULT 'sent'::text CHECK (delivery_status = ANY (ARRAY['sent'::text, 'failed'::text, 'opened'::text])),
  CONSTRAINT challenge_nudge_logs_pkey PRIMARY KEY (id),
  CONSTRAINT challenge_nudge_logs_nudge_id_fkey FOREIGN KEY (nudge_id) REFERENCES public.challenge_nudges(id)
);
CREATE TABLE public.challenge_nudges (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  challenge_id uuid NOT NULL,
  tenant_id uuid NOT NULL,
  nudge_type USER-DEFINED NOT NULL,
  trigger_condition text NOT NULL,
  trigger_days_before integer,
  message_template text NOT NULL,
  is_active boolean DEFAULT true,
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  updated_at timestamp with time zone NOT NULL DEFAULT now(),
  CONSTRAINT challenge_nudges_pkey PRIMARY KEY (id),
  CONSTRAINT challenge_nudges_challenge_id_fkey FOREIGN KEY (challenge_id) REFERENCES public.challenges(id),
  CONSTRAINT challenge_nudges_tenant_id_fkey FOREIGN KEY (tenant_id) REFERENCES public.tenants(id)
);
CREATE TABLE public.challenge_participants (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  challenge_id uuid NOT NULL,
  user_id uuid NOT NULL,
  tenant_id uuid NOT NULL,
  joined_at timestamp with time zone NOT NULL DEFAULT now(),
  registration_type USER-DEFINED NOT NULL,
  current_progress integer DEFAULT 0,
  progress_percentage numeric DEFAULT 0,
  total_points integer DEFAULT 0,
  actions_completed integer DEFAULT 0,
  tier_achieved USER-DEFINED,
  tier_achieved_at timestamp with time zone,
  status USER-DEFINED NOT NULL DEFAULT 'active'::challenge_participant_status,
  completed_at timestamp with time zone,
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  updated_at timestamp with time zone NOT NULL DEFAULT now(),
  CONSTRAINT challenge_participants_pkey PRIMARY KEY (id),
  CONSTRAINT challenge_participants_challenge_id_fkey FOREIGN KEY (challenge_id) REFERENCES public.challenges(id),
  CONSTRAINT challenge_participants_tenant_id_fkey FOREIGN KEY (tenant_id) REFERENCES public.tenants(id)
);
CREATE TABLE public.challenges (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  tenant_id uuid NOT NULL,
  name text NOT NULL,
  description text NOT NULL,
  objective text NOT NULL,
  family USER-DEFINED NOT NULL,
  challenge_type USER-DEFINED NOT NULL,
  start_date timestamp with time zone NOT NULL,
  end_date timestamp with time zone NOT NULL,
  target_audience jsonb NOT NULL DEFAULT '{"ids": [], "type": "all"}'::jsonb,
  progress_type USER-DEFINED NOT NULL,
  target_metric text,
  target_value integer,
  points_per_action integer DEFAULT 1,
  completion_bonus integer DEFAULT 3,
  enable_tiers boolean DEFAULT false,
  tier_bronze_threshold integer DEFAULT 60,
  tier_silver_threshold integer DEFAULT 80,
  tier_gold_threshold integer DEFAULT 100,
  badge_id uuid,
  status USER-DEFINED NOT NULL DEFAULT 'draft'::challenge_status,
  created_by uuid,
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  updated_at timestamp with time zone NOT NULL DEFAULT now(),
  archived_at timestamp with time zone,
  progress_sources jsonb DEFAULT '[]'::jsonb,
  scoring_weights jsonb DEFAULT '{"kpi": 60, "growth": 15, "values": 25}'::jsonb,
  fair_play_rules jsonb DEFAULT '{"normalize_kpis": false, "limit_same_person": 3, "require_validation": false}'::jsonb,
  nudges_config jsonb DEFAULT '{"enabled": false, "messages": []}'::jsonb,
  impact_metrics jsonb DEFAULT '{}'::jsonb,
  metas jsonb DEFAULT '[]'::jsonb,
  icon text NOT NULL DEFAULT 'Target'::text,
  color text NOT NULL DEFAULT '#3B82F6'::text,
  bg_color text NOT NULL DEFAULT '#EFF6FF'::text,
  CONSTRAINT challenges_pkey PRIMARY KEY (id),
  CONSTRAINT challenges_tenant_id_fkey FOREIGN KEY (tenant_id) REFERENCES public.tenants(id),
  CONSTRAINT challenges_badge_id_fkey FOREIGN KEY (badge_id) REFERENCES public.badges(id)
);
CREATE TABLE public.departments (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  tenant_id uuid NOT NULL,
  name text NOT NULL,
  description text,
  manager_id uuid,
  parent_department_id uuid,
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  updated_at timestamp with time zone NOT NULL DEFAULT now(),
  archived_at timestamp with time zone,
  CONSTRAINT departments_pkey PRIMARY KEY (id),
  CONSTRAINT departments_tenant_id_fkey FOREIGN KEY (tenant_id) REFERENCES public.tenants(id),
  CONSTRAINT departments_manager_id_fkey FOREIGN KEY (manager_id) REFERENCES public.profiles(id),
  CONSTRAINT departments_parent_department_id_fkey FOREIGN KEY (parent_department_id) REFERENCES public.departments(id)
);
CREATE TABLE public.funding_orders (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  tenant_id uuid NOT NULL,
  provider text DEFAULT 'DLOCAL'::text,
  status USER-DEFINED DEFAULT 'CREATED'::funding_status,
  amount_local numeric NOT NULL CHECK (amount_local > 0::numeric),
  currency USER-DEFINED NOT NULL,
  points_to_credit numeric NOT NULL CHECK (points_to_credit > 0::numeric),
  fx_rate_to_point numeric,
  provider_payment_id text,
  provider_payload jsonb DEFAULT '{}'::jsonb,
  idempotency_key text,
  created_by uuid,
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  CONSTRAINT funding_orders_pkey PRIMARY KEY (id),
  CONSTRAINT funding_orders_tenant_id_fkey FOREIGN KEY (tenant_id) REFERENCES public.tenants(id)
);
CREATE TABLE public.gift_card_batches (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  tenant_id uuid NOT NULL,
  created_by uuid NOT NULL,
  status text NOT NULL DEFAULT 'pending'::text CHECK (status = ANY (ARRAY['pending'::text, 'processing'::text, 'completed'::text, 'failed'::text, 'cancelled'::text])),
  catalog_item_id uuid NOT NULL,
  denomination numeric NOT NULL,
  currency text NOT NULL,
  provider_id text NOT NULL,
  total_recipients integer NOT NULL DEFAULT 0,
  total_orders integer NOT NULL DEFAULT 0,
  fulfilled_orders integer NOT NULL DEFAULT 0,
  failed_orders integer NOT NULL DEFAULT 0,
  pending_orders integer NOT NULL DEFAULT 0,
  total_amount numeric NOT NULL DEFAULT 0,
  custom_message text,
  scheduled_for timestamp with time zone,
  metadata jsonb DEFAULT '{}'::jsonb,
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  completed_at timestamp with time zone,
  CONSTRAINT gift_card_batches_pkey PRIMARY KEY (id),
  CONSTRAINT gift_card_batches_tenant_id_fkey FOREIGN KEY (tenant_id) REFERENCES public.tenants(id),
  CONSTRAINT gift_card_batches_provider_id_fkey FOREIGN KEY (provider_id) REFERENCES public.providers(id),
  CONSTRAINT gift_card_batches_created_by_fkey FOREIGN KEY (created_by) REFERENCES public.profiles(id),
  CONSTRAINT fk_catalog_item_id FOREIGN KEY (catalog_item_id) REFERENCES public.reward_items(id)
);
CREATE TABLE public.global_provider_configs (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  provider_id text NOT NULL UNIQUE,
  mode text NOT NULL DEFAULT 'tenant'::text,
  endpoint text,
  funding_source_id text,
  metadata jsonb DEFAULT '{}'::jsonb,
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  updated_at timestamp with time zone NOT NULL DEFAULT now(),
  CONSTRAINT global_provider_configs_pkey PRIMARY KEY (id)
);
CREATE TABLE public.liability_snapshots (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  tenant_id uuid NOT NULL,
  snapshot_date date NOT NULL,
  redeemable_points bigint NOT NULL,
  assumed_eur_per_point numeric NOT NULL,
  wallet_available_eur numeric NOT NULL,
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  currency text NOT NULL DEFAULT 'CLP'::text,
  points_to_currency_rate numeric NOT NULL DEFAULT 1.0,
  wallet_available_local numeric,
  exposure_local numeric,
  CONSTRAINT liability_snapshots_pkey PRIMARY KEY (id)
);
CREATE TABLE public.nominations (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  tenant_id uuid NOT NULL,
  award_id uuid NOT NULL,
  nominee_id uuid NOT NULL,
  nominee_name text NOT NULL,
  nominee_avatar text,
  nominator_id uuid NOT NULL,
  nominator_name text NOT NULL,
  department text,
  reason text NOT NULL,
  attachments ARRAY,
  values ARRAY,
  status text NOT NULL DEFAULT 'received'::text CHECK (status = ANY (ARRAY['received'::text, 'in-review'::text, 'approved'::text, 'rejected'::text, 'candidate'::text, 'winner'::text])),
  moderation_flags ARRAY,
  votes integer NOT NULL DEFAULT 0,
  score numeric,
  submitted_at timestamp with time zone NOT NULL DEFAULT now(),
  reviewed_at timestamp with time zone,
  reviewed_by uuid,
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  updated_at timestamp with time zone NOT NULL DEFAULT now(),
  CONSTRAINT nominations_pkey PRIMARY KEY (id),
  CONSTRAINT nominations_award_id_fkey FOREIGN KEY (award_id) REFERENCES public.awards(id)
);
CREATE TABLE public.occasions (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  tenant_id uuid NOT NULL,
  name text NOT NULL,
  description text NOT NULL,
  icon text NOT NULL,
  color text NOT NULL,
  bg_color text NOT NULL,
  status USER-DEFINED NOT NULL DEFAULT 'draft'::occasion_status,
  active boolean NOT NULL DEFAULT false,
  archived_at timestamp with time zone,
  version integer NOT NULL DEFAULT 1,
  usage_this_month integer NOT NULL DEFAULT 0,
  templates_count integer NOT NULL DEFAULT 0,
  frequency text NOT NULL DEFAULT 'Ilimitado'::text,
  auto_trigger boolean NOT NULL DEFAULT false,
  trigger_date_type text,
  trigger_offset_days integer DEFAULT 0,
  notification_enabled boolean NOT NULL DEFAULT true,
  ecard_templates ARRAY,
  organizational_events text,
  visibility USER-DEFINED NOT NULL DEFAULT 'public'::visibility_type,
  requires_approval boolean NOT NULL DEFAULT false,
  allowed_granters USER-DEFINED NOT NULL DEFAULT 'all'::allowed_granters,
  custom_granters text,
  allowed_origins ARRAY NOT NULL DEFAULT ARRAY['app'::allowed_origin],
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  updated_at timestamp with time zone NOT NULL DEFAULT now(),
  CONSTRAINT occasions_pkey PRIMARY KEY (id)
);
CREATE TABLE public.organizational_values (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  tenant_id uuid NOT NULL,
  name text NOT NULL,
  description text,
  icon text NOT NULL DEFAULT 'Heart'::text,
  color text NOT NULL DEFAULT '#3B82F6'::text,
  bg_color text NOT NULL DEFAULT '#EFF6FF'::text,
  sort_order integer NOT NULL DEFAULT 0,
  status text NOT NULL DEFAULT 'active'::text CHECK (status = ANY (ARRAY['active'::text, 'archived'::text])),
  usage_count integer NOT NULL DEFAULT 0,
  archived_at timestamp with time zone,
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  updated_at timestamp with time zone NOT NULL DEFAULT now(),
  CONSTRAINT organizational_values_pkey PRIMARY KEY (id),
  CONSTRAINT organizational_values_tenant_id_fkey FOREIGN KEY (tenant_id) REFERENCES public.tenants(id)
);
CREATE TABLE public.point_transactions (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  tenant_id uuid NOT NULL,
  recognition_id uuid,
  user_id uuid NOT NULL,
  transaction_type USER-DEFINED NOT NULL,
  points_delta integer NOT NULL,
  balance_before integer NOT NULL,
  balance_after integer NOT NULL CHECK (balance_after >= 0),
  expires_at timestamp with time zone,
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  metadata jsonb DEFAULT '{}'::jsonb,
  CONSTRAINT point_transactions_pkey PRIMARY KEY (id),
  CONSTRAINT point_transactions_recognition_id_fkey FOREIGN KEY (recognition_id) REFERENCES public.recognitions(id)
);
CREATE TABLE public.profiles (
  id uuid NOT NULL,
  email text NOT NULL,
  first_name text,
  last_name text,
  display_name text,
  avatar_url text,
  phone text,
  department text,
  position text,
  is_active boolean NOT NULL DEFAULT true,
  last_login_at timestamp with time zone,
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  updated_at timestamp with time zone NOT NULL DEFAULT now(),
  manager_id uuid,
  date_of_birth date,
  hire_date date,
  CONSTRAINT profiles_pkey PRIMARY KEY (id),
  CONSTRAINT profiles_id_fkey FOREIGN KEY (id) REFERENCES auth.users(id),
  CONSTRAINT profiles_manager_id_fkey FOREIGN KEY (manager_id) REFERENCES public.profiles(id)
);
CREATE TABLE public.provider_audit_logs (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  tenant_id uuid NOT NULL,
  provider_id text NOT NULL,
  config_id uuid,
  user_id uuid NOT NULL,
  action text NOT NULL CHECK (action = ANY (ARRAY['connected'::text, 'disconnected'::text, 'updated'::text, 'set_default'::text, 'test_connection'::text])),
  old_values jsonb,
  new_values jsonb,
  metadata jsonb DEFAULT '{}'::jsonb,
  created_at timestamp with time zone DEFAULT now(),
  CONSTRAINT provider_audit_logs_pkey PRIMARY KEY (id),
  CONSTRAINT provider_audit_logs_config_id_fkey FOREIGN KEY (config_id) REFERENCES public.tenant_provider_configs(id)
);
CREATE TABLE public.providers (
  id text NOT NULL,
  name text NOT NULL,
  description text,
  logo_url text,
  category text NOT NULL DEFAULT 'rewards'::text,
  supported_countries ARRAY DEFAULT ARRAY[]::text[],
  supported_currencies ARRAY DEFAULT ARRAY[]::text[],
  requires_api_key boolean DEFAULT true,
  requires_client_id boolean DEFAULT false,
  requires_client_secret boolean DEFAULT false,
  requires_region boolean DEFAULT false,
  webhook_supported boolean DEFAULT false,
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  CONSTRAINT providers_pkey PRIMARY KEY (id)
);
CREATE TABLE public.recognition_approvals (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  recognition_id uuid NOT NULL,
  approver_id uuid NOT NULL,
  status USER-DEFINED NOT NULL DEFAULT 'pending'::approval_status,
  comments text,
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  updated_at timestamp with time zone NOT NULL DEFAULT now(),
  transaction_id uuid,
  CONSTRAINT recognition_approvals_pkey PRIMARY KEY (id),
  CONSTRAINT recognition_approvals_recognition_id_fkey FOREIGN KEY (recognition_id) REFERENCES public.recognitions(id),
  CONSTRAINT recognition_approvals_transaction_id_fkey FOREIGN KEY (transaction_id) REFERENCES public.recognition_transactions(id)
);
CREATE TABLE public.recognition_budget_ledger (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  tenant_id uuid NOT NULL,
  budget_id uuid NOT NULL,
  tx_type USER-DEFINED NOT NULL,
  points_delta integer NOT NULL,
  related_object jsonb,
  note text,
  actor_user_id uuid,
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  point_transaction_id uuid,
  CONSTRAINT recognition_budget_ledger_pkey PRIMARY KEY (id),
  CONSTRAINT recognition_budget_ledger_budget_id_fkey FOREIGN KEY (budget_id) REFERENCES public.recognition_budgets(id),
  CONSTRAINT fk_point_transaction FOREIGN KEY (point_transaction_id) REFERENCES public.point_transactions(id)
);
CREATE TABLE public.recognition_budgets (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  tenant_id uuid NOT NULL,
  scope_id uuid NOT NULL,
  period_start date NOT NULL,
  period_end date NOT NULL,
  hard_cap_points integer NOT NULL CHECK (hard_cap_points >= 0),
  soft_cap_points integer NOT NULL CHECK (soft_cap_points >= 0),
  carryover_policy text NOT NULL CHECK (carryover_policy = ANY (ARRAY['none'::text, 'unused_to_next'::text, 'percent_to_next'::text])),
  carryover_percent integer CHECK (carryover_percent >= 0 AND carryover_percent <= 100),
  allocated_points integer NOT NULL DEFAULT 0,
  consumed_points integer NOT NULL DEFAULT 0,
  is_locked boolean NOT NULL DEFAULT false,
  is_published boolean NOT NULL DEFAULT true,
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  updated_at timestamp with time zone NOT NULL DEFAULT now(),
  CONSTRAINT recognition_budgets_pkey PRIMARY KEY (id),
  CONSTRAINT recognition_budgets_scope_id_fkey FOREIGN KEY (scope_id) REFERENCES public.recognition_scopes(id)
);
CREATE TABLE public.recognition_comments (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  tenant_id uuid NOT NULL,
  transaction_id uuid NOT NULL,
  user_id uuid NOT NULL,
  comment_text text NOT NULL CHECK (length(TRIM(BOTH FROM comment_text)) > 0 AND length(comment_text) <= 1000),
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  updated_at timestamp with time zone NOT NULL DEFAULT now(),
  edited boolean NOT NULL DEFAULT false,
  CONSTRAINT recognition_comments_pkey PRIMARY KEY (id),
  CONSTRAINT recognition_comments_tenant_id_fkey FOREIGN KEY (tenant_id) REFERENCES public.tenants(id),
  CONSTRAINT recognition_comments_transaction_id_fkey FOREIGN KEY (transaction_id) REFERENCES public.recognition_transactions(id),
  CONSTRAINT recognition_comments_user_id_fkey FOREIGN KEY (user_id) REFERENCES public.profiles(id)
);
CREATE TABLE public.recognition_reactions (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  tenant_id uuid NOT NULL,
  transaction_id uuid NOT NULL,
  user_id uuid NOT NULL,
  reaction_type text NOT NULL DEFAULT 'like'::text CHECK (reaction_type = ANY (ARRAY['like'::text, 'love'::text, 'celebrate'::text, 'clap'::text])),
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  CONSTRAINT recognition_reactions_pkey PRIMARY KEY (id),
  CONSTRAINT recognition_reactions_tenant_id_fkey FOREIGN KEY (tenant_id) REFERENCES public.tenants(id),
  CONSTRAINT recognition_reactions_transaction_id_fkey FOREIGN KEY (transaction_id) REFERENCES public.recognition_transactions(id)
);
CREATE TABLE public.recognition_recipients (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  transaction_id uuid NOT NULL,
  recipient_id uuid NOT NULL,
  recipient_type text NOT NULL CHECK (recipient_type = ANY (ARRAY['individual'::text, 'department_member'::text, 'team_member'::text])),
  points_awarded integer NOT NULL DEFAULT 0,
  status text NOT NULL DEFAULT 'pending'::text CHECK (status = ANY (ARRAY['pending'::text, 'processed'::text, 'failed'::text])),
  processed_at timestamp with time zone,
  error_message text,
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  CONSTRAINT recognition_recipients_pkey PRIMARY KEY (id),
  CONSTRAINT recognition_recipients_transaction_id_fkey FOREIGN KEY (transaction_id) REFERENCES public.recognition_transactions(id),
  CONSTRAINT recognition_recipients_receiver_id_fkey FOREIGN KEY (recipient_id) REFERENCES public.profiles(id)
);
CREATE TABLE public.recognition_scopes (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  tenant_id uuid NOT NULL,
  scope_type text NOT NULL CHECK (scope_type = ANY (ARRAY['company'::text, 'department'::text, 'team'::text, 'manager'::text, 'user'::text])),
  department_id uuid,
  team_id uuid,
  manager_user_id uuid,
  user_id uuid,
  name text NOT NULL,
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  updated_at timestamp with time zone NOT NULL DEFAULT now(),
  CONSTRAINT recognition_scopes_pkey PRIMARY KEY (id),
  CONSTRAINT recognition_scopes_department_id_fkey FOREIGN KEY (department_id) REFERENCES public.departments(id),
  CONSTRAINT recognition_scopes_team_id_fkey FOREIGN KEY (team_id) REFERENCES public.teams(id)
);
CREATE TABLE public.recognition_snapshots (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  recognition_id uuid NOT NULL,
  recognition_type_config jsonb NOT NULL DEFAULT '{}'::jsonb,
  organizational_values_active jsonb NOT NULL DEFAULT '[]'::jsonb,
  points_config jsonb NOT NULL DEFAULT '{}'::jsonb,
  approval_rules jsonb NOT NULL DEFAULT '{}'::jsonb,
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  CONSTRAINT recognition_snapshots_pkey PRIMARY KEY (id),
  CONSTRAINT recognition_snapshots_recognition_id_fkey FOREIGN KEY (recognition_id) REFERENCES public.recognitions(id)
);
CREATE TABLE public.recognition_transactions (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  tenant_id uuid NOT NULL,
  giver_id uuid NOT NULL,
  transaction_type text NOT NULL CHECK (transaction_type = ANY (ARRAY['recognition_type'::text, 'occasion'::text, 'automatic_event'::text, 'award'::text])),
  recognition_type_id uuid,
  source_type text NOT NULL DEFAULT 'manual'::text CHECK (source_type = ANY (ARRAY['recognition_type'::text, 'occasion'::text, 'automatic_event'::text, 'award'::text])),
  source_id uuid,
  status text NOT NULL DEFAULT 'draft'::text CHECK (status = ANY (ARRAY['draft'::text, 'pending_approval'::text, 'approved'::text, 'rejected'::text, 'completed'::text, 'failed'::text])),
  total_recipients integer NOT NULL DEFAULT 0,
  total_points_awarded integer NOT NULL DEFAULT 0,
  points_per_recipient integer NOT NULL DEFAULT 0,
  message text,
  metadata jsonb DEFAULT '{}'::jsonb,
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  updated_at timestamp with time zone NOT NULL DEFAULT now(),
  completed_at timestamp with time zone,
  source_reference_id uuid,
  source_reference_type text,
  visibility USER-DEFINED NOT NULL DEFAULT 'public'::visibility_type,
  CONSTRAINT recognition_transactions_pkey PRIMARY KEY (id),
  CONSTRAINT recognition_transactions_tenant_id_fkey FOREIGN KEY (tenant_id) REFERENCES public.tenants(id),
  CONSTRAINT recognition_transactions_recognition_type_id_fkey FOREIGN KEY (recognition_type_id) REFERENCES public.recognition_types(id),
  CONSTRAINT recognition_transactions_giver_id_fkey FOREIGN KEY (giver_id) REFERENCES public.profiles(id)
);
CREATE TABLE public.recognition_types (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  tenant_id uuid NOT NULL,
  name text NOT NULL CHECK (length(name) >= 1 AND length(name) <= 100),
  description text NOT NULL CHECK (length(description) >= 1 AND length(description) <= 255),
  icon text NOT NULL,
  color text NOT NULL,
  bg_color text NOT NULL,
  status USER-DEFINED NOT NULL DEFAULT 'draft'::recognition_status,
  active boolean NOT NULL DEFAULT false,
  archived_at timestamp with time zone,
  version integer NOT NULL DEFAULT 1,
  usage_this_month integer NOT NULL DEFAULT 0,
  points_min integer,
  points_max integer,
  default_points integer,
  point_range text,
  points_expiry text,
  frequency text NOT NULL DEFAULT 'Ilimitado'::text,
  max_per_person_month integer,
  max_per_team_month integer,
  allowed_granters USER-DEFINED DEFAULT 'all'::allowed_granters,
  custom_granters text,
  allowed_origins ARRAY DEFAULT ARRAY['app'::allowed_origin],
  allows_video boolean DEFAULT false,
  allows_multiple_recipients boolean DEFAULT false,
  allows_team_recognition boolean DEFAULT false,
  use_team_budget boolean DEFAULT false,
  visibility USER-DEFINED DEFAULT 'public'::visibility_type,
  requires_approval boolean DEFAULT false,
  organizational_values text,
  associated_badges text,
  related_events text,
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  updated_at timestamp with time zone NOT NULL DEFAULT now(),
  is_flash_mode boolean NOT NULL DEFAULT false,
  CONSTRAINT recognition_types_pkey PRIMARY KEY (id),
  CONSTRAINT recognition_types_tenant_id_fkey FOREIGN KEY (tenant_id) REFERENCES public.tenants(id)
);
CREATE TABLE public.recognitions (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  tenant_id uuid NOT NULL,
  recognition_type_id uuid,
  giver_id uuid NOT NULL,
  receiver_id uuid NOT NULL,
  receiver_team_id uuid,
  source_type USER-DEFINED NOT NULL DEFAULT 'manual'::recognition_source,
  source_id uuid,
  status USER-DEFINED NOT NULL DEFAULT 'draft'::recognition_status,
  message text,
  points_awarded integer NOT NULL DEFAULT 0 CHECK (points_awarded >= 0),
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  updated_at timestamp with time zone NOT NULL DEFAULT now(),
  completed_at timestamp with time zone,
  metadata jsonb DEFAULT '{}'::jsonb,
  CONSTRAINT recognitions_pkey PRIMARY KEY (id),
  CONSTRAINT recognitions_recognition_type_id_fkey FOREIGN KEY (recognition_type_id) REFERENCES public.recognition_types(id)
);
CREATE TABLE public.redemption_orders (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  batch_id uuid,
  tenant_id uuid NOT NULL,
  user_id uuid NOT NULL,
  recipient_email text NOT NULL,
  recipient_name text NOT NULL,
  catalog_item_id uuid NOT NULL,
  provider_id text NOT NULL,
  denomination numeric NOT NULL,
  currency text NOT NULL,
  status text NOT NULL DEFAULT 'pending'::text CHECK (status = ANY (ARRAY['pending'::text, 'processing'::text, 'fulfilled'::text, 'failed'::text, 'cancelled'::text])),
  external_id text,
  external_order_id text,
  idempotency_key text NOT NULL UNIQUE,
  custom_message text,
  error_message text,
  redemption_url text,
  redemption_code text,
  provider_response jsonb,
  metadata jsonb DEFAULT '{}'::jsonb,
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  fulfilled_at timestamp with time zone,
  failed_at timestamp with time zone,
  CONSTRAINT redemption_orders_pkey PRIMARY KEY (id),
  CONSTRAINT redemption_orders_batch_id_fkey FOREIGN KEY (batch_id) REFERENCES public.gift_card_batches(id),
  CONSTRAINT redemption_orders_tenant_id_fkey FOREIGN KEY (tenant_id) REFERENCES public.tenants(id),
  CONSTRAINT redemption_orders_provider_id_fkey FOREIGN KEY (provider_id) REFERENCES public.providers(id),
  CONSTRAINT fk_redemption_orders_catalog_item FOREIGN KEY (catalog_item_id) REFERENCES public.reward_items(id)
);
CREATE TABLE public.reward_catalog_items (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  provider_id text NOT NULL,
  external_id text NOT NULL,
  brand text NOT NULL,
  country text NOT NULL,
  currency text NOT NULL,
  denom_min numeric NOT NULL,
  denom_max numeric NOT NULL,
  tags ARRAY DEFAULT ARRAY[]::text[],
  available boolean NOT NULL DEFAULT true,
  visible boolean NOT NULL DEFAULT false,
  selectable boolean NOT NULL DEFAULT true,
  metadata jsonb DEFAULT '{}'::jsonb,
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  CONSTRAINT reward_catalog_items_pkey PRIMARY KEY (id),
  CONSTRAINT reward_catalog_items_provider_id_fkey FOREIGN KEY (provider_id) REFERENCES public.providers(id)
);
CREATE TABLE public.reward_categories (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  tenant_id uuid NOT NULL,
  name text NOT NULL,
  description text,
  icon text NOT NULL DEFAULT 'ShoppingBag'::text,
  color text NOT NULL DEFAULT '#3B82F6'::text,
  bg_color text NOT NULL DEFAULT '#EFF6FF'::text,
  matching_rules jsonb NOT NULL DEFAULT '[]'::jsonb,
  sort_order integer NOT NULL DEFAULT 0,
  visible boolean NOT NULL DEFAULT true,
  is_featured boolean NOT NULL DEFAULT false,
  items_count integer NOT NULL DEFAULT 0,
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  CONSTRAINT reward_categories_pkey PRIMARY KEY (id),
  CONSTRAINT reward_categories_tenant_id_fkey FOREIGN KEY (tenant_id) REFERENCES public.tenants(id)
);
CREATE TABLE public.reward_featured_items (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  tenant_id uuid NOT NULL,
  reward_item_id uuid NOT NULL,
  title text,
  description text,
  sort_order integer NOT NULL DEFAULT 0,
  featured_from timestamp with time zone DEFAULT now(),
  featured_until timestamp with time zone,
  created_by uuid NOT NULL,
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  CONSTRAINT reward_featured_items_pkey PRIMARY KEY (id),
  CONSTRAINT reward_featured_items_reward_item_id_fkey FOREIGN KEY (reward_item_id) REFERENCES public.reward_items(id),
  CONSTRAINT reward_featured_items_tenant_id_fkey FOREIGN KEY (tenant_id) REFERENCES public.tenants(id)
);
CREATE TABLE public.reward_item_categories (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  tenant_id uuid NOT NULL,
  reward_item_id uuid NOT NULL,
  category_id uuid NOT NULL,
  assignment_type text NOT NULL DEFAULT 'auto'::text,
  assigned_by uuid,
  assigned_at timestamp with time zone DEFAULT now(),
  created_at timestamp with time zone DEFAULT now(),
  CONSTRAINT reward_item_categories_pkey PRIMARY KEY (id),
  CONSTRAINT reward_item_categories_tenant_id_fkey FOREIGN KEY (tenant_id) REFERENCES public.tenants(id),
  CONSTRAINT reward_item_categories_reward_item_id_fkey FOREIGN KEY (reward_item_id) REFERENCES public.reward_items(id),
  CONSTRAINT reward_item_categories_category_id_fkey FOREIGN KEY (category_id) REFERENCES public.reward_categories(id)
);
CREATE TABLE public.reward_items (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  provider_id text NOT NULL,
  external_id text NOT NULL,
  brand text NOT NULL,
  country text NOT NULL,
  currency text NOT NULL,
  denom_min numeric NOT NULL,
  denom_max numeric NOT NULL,
  tags ARRAY DEFAULT '{}'::text[],
  available boolean NOT NULL DEFAULT true,
  updated_at timestamp with time zone NOT NULL DEFAULT now(),
  tremendous_product_id text,
  provider_data jsonb DEFAULT '{}'::jsonb,
  skus jsonb DEFAULT '[]'::jsonb,
  fulfillment_type text CHECK (fulfillment_type = ANY (ARRAY['internal'::text, 'external'::text, 'prepaid_stock'::text])),
  cost_source text CHECK (cost_source = ANY (ARRAY['none'::text, 'wallet'::text, 'prepaid_stock'::text])),
  unit_price numeric,
  currency_code text,
  enabled_when_cr numeric DEFAULT 0.00,
  requires_approval boolean DEFAULT false,
  sla_hours integer,
  stock_qty integer,
  CONSTRAINT reward_items_pkey PRIMARY KEY (id)
);
CREATE TABLE public.reward_redemptions (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  tenant_id uuid NOT NULL,
  user_id uuid NOT NULL,
  reward_item_id uuid NOT NULL,
  points_spent integer NOT NULL,
  wallet_amount_local numeric NOT NULL,
  wallet_currency text NOT NULL,
  fx_rate numeric,
  status text NOT NULL DEFAULT 'pending'::text,
  provider_id text NOT NULL,
  provider_order_id text,
  point_tx_id uuid,
  wallet_ledger_id uuid,
  idempotency_key text UNIQUE,
  created_at timestamp with time zone DEFAULT now(),
  fulfilled_at timestamp with time zone,
  metadata jsonb DEFAULT '{}'::jsonb,
  CONSTRAINT reward_redemptions_pkey PRIMARY KEY (id),
  CONSTRAINT reward_redemptions_point_tx_id_fkey FOREIGN KEY (point_tx_id) REFERENCES public.point_transactions(id),
  CONSTRAINT reward_redemptions_wallet_ledger_id_fkey FOREIGN KEY (wallet_ledger_id) REFERENCES public.wallet_ledger(id)
);
CREATE TABLE public.sso_tokens (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  token text NOT NULL UNIQUE,
  access_token text NOT NULL,
  refresh_token text NOT NULL,
  user_id uuid NOT NULL,
  tenant_id uuid NOT NULL,
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  expires_at timestamp with time zone NOT NULL DEFAULT (now() + '00:00:30'::interval),
  used_at timestamp with time zone,
  CONSTRAINT sso_tokens_pkey PRIMARY KEY (id)
);
CREATE TABLE public.teams (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  tenant_id uuid NOT NULL,
  department_id uuid NOT NULL,
  name text NOT NULL,
  description text,
  manager_id uuid,
  parent_team_id uuid,
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  updated_at timestamp with time zone NOT NULL DEFAULT now(),
  archived_at timestamp with time zone,
  CONSTRAINT teams_pkey PRIMARY KEY (id),
  CONSTRAINT teams_tenant_id_fkey FOREIGN KEY (tenant_id) REFERENCES public.tenants(id),
  CONSTRAINT teams_department_id_fkey FOREIGN KEY (department_id) REFERENCES public.departments(id),
  CONSTRAINT teams_manager_id_fkey FOREIGN KEY (manager_id) REFERENCES public.profiles(id),
  CONSTRAINT teams_parent_team_id_fkey FOREIGN KEY (parent_team_id) REFERENCES public.teams(id)
);
CREATE TABLE public.tenant_feature_flags (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  tenant_id uuid NOT NULL,
  flag_key text NOT NULL,
  enabled boolean DEFAULT false,
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  CONSTRAINT tenant_feature_flags_pkey PRIMARY KEY (id),
  CONSTRAINT tenant_feature_flags_tenant_id_fkey FOREIGN KEY (tenant_id) REFERENCES public.tenants(id)
);
CREATE TABLE public.tenant_integrations (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  tenant_id uuid NOT NULL,
  integration_type text NOT NULL,
  config jsonb NOT NULL DEFAULT '{}'::jsonb,
  metadata jsonb,
  is_active boolean NOT NULL DEFAULT false,
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  updated_at timestamp with time zone NOT NULL DEFAULT now(),
  created_by uuid,
  CONSTRAINT tenant_integrations_pkey PRIMARY KEY (id),
  CONSTRAINT tenant_integrations_tenant_id_fkey FOREIGN KEY (tenant_id) REFERENCES public.tenants(id),
  CONSTRAINT tenant_integrations_created_by_fkey FOREIGN KEY (created_by) REFERENCES auth.users(id)
);
CREATE TABLE public.tenant_invitations (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  tenant_id uuid NOT NULL,
  email text NOT NULL,
  role USER-DEFINED NOT NULL DEFAULT 'user'::app_role,
  token text NOT NULL UNIQUE,
  invited_by uuid,
  expires_at timestamp with time zone NOT NULL DEFAULT (now() + '7 days'::interval),
  used_at timestamp with time zone,
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  updated_at timestamp with time zone NOT NULL DEFAULT now(),
  CONSTRAINT tenant_invitations_pkey PRIMARY KEY (id),
  CONSTRAINT tenant_invitations_tenant_id_fkey FOREIGN KEY (tenant_id) REFERENCES public.tenants(id),
  CONSTRAINT tenant_invitations_invited_by_fkey FOREIGN KEY (invited_by) REFERENCES auth.users(id)
);
CREATE TABLE public.tenant_provider_configs (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  tenant_id uuid NOT NULL,
  provider_id text NOT NULL,
  status text NOT NULL DEFAULT 'disabled'::text CHECK (status = ANY (ARRAY['enabled'::text, 'disabled'::text, 'error'::text])),
  is_default boolean DEFAULT false,
  priority integer DEFAULT 0,
  api_key text,
  client_id text,
  client_secret text,
  region text,
  endpoint text,
  allowed_countries ARRAY DEFAULT ARRAY[]::text[],
  allowed_currencies ARRAY DEFAULT ARRAY[]::text[],
  daily_limit integer,
  monthly_limit integer,
  webhook_url text,
  webhook_secret text,
  last_test_at timestamp with time zone,
  last_test_status text CHECK (last_test_status = ANY (ARRAY['success'::text, 'failed'::text])),
  last_test_message text,
  metadata jsonb DEFAULT '{}'::jsonb,
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  created_by uuid,
  CONSTRAINT tenant_provider_configs_pkey PRIMARY KEY (id),
  CONSTRAINT tenant_provider_configs_tenant_id_fkey FOREIGN KEY (tenant_id) REFERENCES public.tenants(id),
  CONSTRAINT tenant_provider_configs_provider_id_fkey FOREIGN KEY (provider_id) REFERENCES public.providers(id)
);
CREATE TABLE public.tenant_reward_visibility (
  tenant_id uuid NOT NULL,
  reward_item_id uuid NOT NULL,
  visible boolean NOT NULL DEFAULT false,
  updated_by uuid,
  updated_at timestamp with time zone NOT NULL DEFAULT now(),
  CONSTRAINT tenant_reward_visibility_pkey PRIMARY KEY (tenant_id, reward_item_id),
  CONSTRAINT tenant_reward_visibility_reward_item_id_fkey FOREIGN KEY (reward_item_id) REFERENCES public.reward_items(id)
);
CREATE TABLE public.tenant_tremendous_mapping (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  tenant_id uuid NOT NULL UNIQUE,
  tremendous_team_id text NOT NULL,
  tremendous_budget_id text,
  funding_source_id text,
  catalog_filter jsonb DEFAULT '[]'::jsonb,
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  updated_at timestamp with time zone NOT NULL DEFAULT now(),
  CONSTRAINT tenant_tremendous_mapping_pkey PRIMARY KEY (id),
  CONSTRAINT tenant_tremendous_mapping_tenant_id_fkey FOREIGN KEY (tenant_id) REFERENCES public.tenants(id)
);
CREATE TABLE public.tenant_wallets (
  tenant_id uuid NOT NULL,
  base_currency USER-DEFINED NOT NULL,
  credit_limit_points numeric DEFAULT 0 CHECK (credit_limit_points >= 0::numeric),
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  CONSTRAINT tenant_wallets_pkey PRIMARY KEY (tenant_id),
  CONSTRAINT tenant_wallets_tenant_id_fkey FOREIGN KEY (tenant_id) REFERENCES public.tenants(id)
);
CREATE TABLE public.tenants (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  name text NOT NULL,
  subdomain text NOT NULL,
  settings jsonb DEFAULT '{"locale": "es-ES", "timezone": "Europe/Madrid", "dateFormat": "dd/MM/yyyy", "currencyCode": "EUR", "numberFormat": "es-ES"}'::jsonb,
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  updated_at timestamp with time zone NOT NULL DEFAULT now(),
  base_currency USER-DEFINED DEFAULT 'USD'::currency_code,
  brand_id uuid NOT NULL,
  CONSTRAINT tenants_pkey PRIMARY KEY (id),
  CONSTRAINT tenants_brand_id_fkey FOREIGN KEY (brand_id) REFERENCES public.brands(id)
);
CREATE TABLE public.training_enrollments (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  tenant_id uuid NOT NULL,
  training_id uuid NOT NULL,
  user_id uuid NOT NULL,
  enrolled_by uuid,
  enrollment_type text NOT NULL CHECK (enrollment_type = ANY (ARRAY['manual'::text, 'auto'::text, 'self'::text])),
  status text NOT NULL DEFAULT 'enrolled'::text CHECK (status = ANY (ARRAY['enrolled'::text, 'in_progress'::text, 'completed'::text, 'dropped'::text])),
  enrolled_at timestamp with time zone NOT NULL DEFAULT now(),
  started_at timestamp with time zone,
  completed_at timestamp with time zone,
  dropped_at timestamp with time zone,
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  updated_at timestamp with time zone NOT NULL DEFAULT now(),
  CONSTRAINT training_enrollments_pkey PRIMARY KEY (id)
);
CREATE TABLE public.training_feed_events (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  tenant_id uuid NOT NULL,
  user_id uuid NOT NULL,
  training_id uuid NOT NULL,
  milestone integer NOT NULL CHECK (milestone = ANY (ARRAY[25, 50, 75, 100])),
  points_earned integer NOT NULL,
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  CONSTRAINT training_feed_events_pkey PRIMARY KEY (id),
  CONSTRAINT fk_training_feed_user FOREIGN KEY (user_id) REFERENCES public.profiles(id),
  CONSTRAINT fk_training_feed_training FOREIGN KEY (training_id) REFERENCES public.trainings(id)
);
CREATE TABLE public.training_micro_missions (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  tenant_id uuid NOT NULL,
  training_id uuid NOT NULL,
  name text NOT NULL,
  description text NOT NULL,
  mission_type USER-DEFINED NOT NULL,
  target_value integer NOT NULL DEFAULT 1,
  points_reward integer NOT NULL DEFAULT 10,
  metadata jsonb DEFAULT '{}'::jsonb,
  is_active boolean NOT NULL DEFAULT true,
  sort_order integer NOT NULL DEFAULT 0,
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  updated_at timestamp with time zone NOT NULL DEFAULT now(),
  CONSTRAINT training_micro_missions_pkey PRIMARY KEY (id),
  CONSTRAINT training_micro_missions_tenant_id_fkey FOREIGN KEY (tenant_id) REFERENCES public.tenants(id),
  CONSTRAINT training_micro_missions_training_id_fkey FOREIGN KEY (training_id) REFERENCES public.trainings(id)
);
CREATE TABLE public.training_progress (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  tenant_id uuid NOT NULL,
  enrollment_id uuid NOT NULL UNIQUE,
  training_id uuid NOT NULL,
  user_id uuid NOT NULL,
  progress_pct integer NOT NULL DEFAULT 0 CHECK (progress_pct >= 0 AND progress_pct <= 100),
  milestones_completed jsonb DEFAULT '[]'::jsonb,
  last_activity_at timestamp with time zone NOT NULL DEFAULT now(),
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  updated_at timestamp with time zone NOT NULL DEFAULT now(),
  breakdown jsonb DEFAULT '{"quizzes": {"ratio": 0, "avg_score": 0, "total_count": 0, "passed_count": 0}, "missions": {"ratio": 0, "total": 0, "completed": 0}, "sections": {"ratio": 0, "total": 0, "completed": 0}}'::jsonb,
  last_recalculated_at timestamp with time zone,
  recalculation_count integer DEFAULT 0,
  CONSTRAINT training_progress_pkey PRIMARY KEY (id),
  CONSTRAINT training_progress_enrollment_id_fkey FOREIGN KEY (enrollment_id) REFERENCES public.training_enrollments(id)
);
CREATE TABLE public.training_quiz_attempts (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  tenant_id uuid NOT NULL,
  user_id uuid NOT NULL,
  training_id uuid NOT NULL,
  section_id uuid NOT NULL,
  enrollment_id uuid,
  attempt_number integer NOT NULL DEFAULT 1,
  score_pct numeric NOT NULL,
  passed boolean NOT NULL,
  answers jsonb NOT NULL,
  correct_count integer NOT NULL,
  total_questions integer NOT NULL,
  started_at timestamp with time zone NOT NULL DEFAULT now(),
  submitted_at timestamp with time zone NOT NULL DEFAULT now(),
  time_taken_seconds integer,
  metadata jsonb DEFAULT '{}'::jsonb,
  CONSTRAINT training_quiz_attempts_pkey PRIMARY KEY (id),
  CONSTRAINT training_quiz_attempts_tenant_id_fkey FOREIGN KEY (tenant_id) REFERENCES public.tenants(id),
  CONSTRAINT training_quiz_attempts_training_id_fkey FOREIGN KEY (training_id) REFERENCES public.trainings(id),
  CONSTRAINT training_quiz_attempts_section_id_fkey FOREIGN KEY (section_id) REFERENCES public.training_sections(id),
  CONSTRAINT training_quiz_attempts_enrollment_id_fkey FOREIGN KEY (enrollment_id) REFERENCES public.training_enrollments(id)
);
CREATE TABLE public.training_section_completions (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  tenant_id uuid NOT NULL,
  user_id uuid NOT NULL,
  training_id uuid NOT NULL,
  section_id uuid NOT NULL,
  enrollment_id uuid,
  completed_at timestamp with time zone NOT NULL DEFAULT now(),
  completion_method text CHECK (completion_method = ANY (ARRAY['manual'::text, 'auto_scroll'::text, 'quiz_passed'::text])),
  time_spent_seconds integer DEFAULT 0,
  metadata jsonb DEFAULT '{}'::jsonb,
  created_at timestamp with time zone DEFAULT now(),
  CONSTRAINT training_section_completions_pkey PRIMARY KEY (id),
  CONSTRAINT training_section_completions_tenant_id_fkey FOREIGN KEY (tenant_id) REFERENCES public.tenants(id),
  CONSTRAINT training_section_completions_training_id_fkey FOREIGN KEY (training_id) REFERENCES public.trainings(id),
  CONSTRAINT training_section_completions_section_id_fkey FOREIGN KEY (section_id) REFERENCES public.training_sections(id),
  CONSTRAINT training_section_completions_enrollment_id_fkey FOREIGN KEY (enrollment_id) REFERENCES public.training_enrollments(id)
);
CREATE TABLE public.training_sections (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  tenant_id uuid NOT NULL,
  training_id uuid NOT NULL,
  title text NOT NULL,
  content_markdown text NOT NULL,
  section_type text NOT NULL DEFAULT 'lesson'::text,
  sort_order integer NOT NULL DEFAULT 0,
  duration_minutes integer,
  learning_objectives ARRAY,
  resources jsonb DEFAULT '[]'::jsonb,
  quiz jsonb,
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  updated_at timestamp with time zone NOT NULL DEFAULT now(),
  CONSTRAINT training_sections_pkey PRIMARY KEY (id),
  CONSTRAINT fk_training_sections_tenant FOREIGN KEY (tenant_id) REFERENCES public.tenants(id),
  CONSTRAINT fk_training_sections_training FOREIGN KEY (training_id) REFERENCES public.trainings(id)
);
CREATE TABLE public.trainings (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  tenant_id uuid NOT NULL,
  title text NOT NULL,
  description text,
  organizational_values ARRAY DEFAULT '{}'::uuid[],
  recognition_type_id uuid,
  points_on_completion integer DEFAULT 50,
  duration_weeks integer NOT NULL DEFAULT 4,
  status text DEFAULT 'draft'::text CHECK (status = ANY (ARRAY['draft'::text, 'active'::text, 'archived'::text])),
  audience text DEFAULT 'all'::text,
  custom_audience ARRAY,
  created_by uuid,
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  archived_at timestamp with time zone,
  metadata jsonb DEFAULT '{}'::jsonb,
  ai_context jsonb DEFAULT '{}'::jsonb,
  ai_suggested_at timestamp with time zone,
  published_at timestamp with time zone,
  sections_count integer DEFAULT 0,
  progress_weights jsonb DEFAULT '{"quizzes": 0.0, "missions": 0.0, "sections": 1.0}'::jsonb,
  milestone_thresholds ARRAY DEFAULT ARRAY[25, 50, 75, 100],
  min_quiz_score_pct integer DEFAULT 70,
  completion_requirements jsonb DEFAULT '{"require_quiz_pass": true, "require_all_missions": false, "require_all_sections": true}'::jsonb,
  CONSTRAINT trainings_pkey PRIMARY KEY (id),
  CONSTRAINT trainings_tenant_id_fkey FOREIGN KEY (tenant_id) REFERENCES public.tenants(id),
  CONSTRAINT trainings_recognition_type_id_fkey FOREIGN KEY (recognition_type_id) REFERENCES public.recognition_types(id)
);
CREATE TABLE public.tremendous_teams_cache (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  team_id text NOT NULL UNIQUE,
  name text NOT NULL,
  budgets jsonb DEFAULT '[]'::jsonb,
  metadata jsonb DEFAULT '{}'::jsonb,
  last_synced_at timestamp with time zone NOT NULL DEFAULT now(),
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  updated_at timestamp with time zone NOT NULL DEFAULT now(),
  CONSTRAINT tremendous_teams_cache_pkey PRIMARY KEY (id)
);
CREATE TABLE public.user_mission_completions (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  tenant_id uuid NOT NULL,
  user_id uuid NOT NULL,
  mission_id uuid NOT NULL,
  training_id uuid NOT NULL,
  current_progress integer NOT NULL DEFAULT 0,
  target_value integer NOT NULL,
  completed boolean NOT NULL DEFAULT false,
  current_streak integer NOT NULL DEFAULT 0,
  longest_streak integer NOT NULL DEFAULT 0,
  last_activity_date date,
  points_earned integer NOT NULL DEFAULT 0,
  recognition_created boolean NOT NULL DEFAULT false,
  started_at timestamp with time zone NOT NULL DEFAULT now(),
  completed_at timestamp with time zone,
  updated_at timestamp with time zone NOT NULL DEFAULT now(),
  metadata jsonb DEFAULT '{}'::jsonb,
  CONSTRAINT user_mission_completions_pkey PRIMARY KEY (id),
  CONSTRAINT user_mission_completions_tenant_id_fkey FOREIGN KEY (tenant_id) REFERENCES public.tenants(id),
  CONSTRAINT user_mission_completions_mission_id_fkey FOREIGN KEY (mission_id) REFERENCES public.training_micro_missions(id),
  CONSTRAINT user_mission_completions_training_id_fkey FOREIGN KEY (training_id) REFERENCES public.trainings(id)
);
CREATE TABLE public.user_organizational_assignments (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  user_id uuid NOT NULL,
  tenant_id uuid NOT NULL,
  department_id uuid,
  team_id uuid,
  is_manager boolean NOT NULL DEFAULT false,
  assigned_at timestamp with time zone NOT NULL DEFAULT now(),
  updated_at timestamp with time zone NOT NULL DEFAULT now(),
  CONSTRAINT user_organizational_assignments_pkey PRIMARY KEY (id),
  CONSTRAINT user_organizational_assignments_user_id_fkey FOREIGN KEY (user_id) REFERENCES public.profiles(id),
  CONSTRAINT user_organizational_assignments_tenant_id_fkey FOREIGN KEY (tenant_id) REFERENCES public.tenants(id),
  CONSTRAINT user_organizational_assignments_department_id_fkey FOREIGN KEY (department_id) REFERENCES public.departments(id),
  CONSTRAINT user_organizational_assignments_team_id_fkey FOREIGN KEY (team_id) REFERENCES public.teams(id)
);
CREATE TABLE public.user_point_balances (
  user_id uuid NOT NULL,
  tenant_id uuid NOT NULL,
  current_balance integer NOT NULL DEFAULT 0 CHECK (current_balance >= 0),
  lifetime_earned integer NOT NULL DEFAULT 0,
  lifetime_spent integer NOT NULL DEFAULT 0,
  pending_points integer NOT NULL DEFAULT 0 CHECK (pending_points >= 0),
  last_transaction_at timestamp with time zone,
  updated_at timestamp with time zone NOT NULL DEFAULT now(),
  CONSTRAINT user_point_balances_pkey PRIMARY KEY (user_id, tenant_id)
);
CREATE TABLE public.user_roles (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  user_id uuid NOT NULL,
  tenant_id uuid NOT NULL,
  role USER-DEFINED NOT NULL,
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  CONSTRAINT user_roles_pkey PRIMARY KEY (id),
  CONSTRAINT user_roles_user_id_fkey FOREIGN KEY (user_id) REFERENCES auth.users(id),
  CONSTRAINT user_roles_tenant_id_fkey FOREIGN KEY (tenant_id) REFERENCES public.tenants(id)
);
CREATE TABLE public.wallet_ledger (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  tenant_id uuid NOT NULL,
  entry_type USER-DEFINED NOT NULL,
  amount_points numeric NOT NULL,
  amount_local numeric,
  currency USER-DEFINED,
  fx_rate_to_point numeric,
  reference_type text,
  reference_id uuid,
  actor_user_id uuid,
  idempotency_key text,
  note text,
  created_at timestamp with time zone DEFAULT now(),
  reference_user_id uuid,
  metadata jsonb DEFAULT '{}'::jsonb,
  CONSTRAINT wallet_ledger_pkey PRIMARY KEY (id),
  CONSTRAINT wallet_ledger_tenant_id_fkey FOREIGN KEY (tenant_id) REFERENCES public.tenants(id)
);